name: Sync Upstream
run-name: Upstream Sync
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions:
    contents: write
    id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "Read Secrets"
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github/rancher-release-team-auto-tagger/app-credentials appId | APP_ID ;
            secret/data/github/repo/${{ github.repository }}/github/rancher-release-team-auto-tagger/app-credentials privateKey | PRIVATE_KEY

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}

      - name: Sync Upstream Releases
        uses: rancher/ecm-distro-tools/actions/sync-upstream-release@master
        with:
          upstream-owner: 'k8snetworkplumbingwg'
          upstream-repo: 'whereabouts'
          image-build-owner: ${{ github.repository_owner }}
          image-build-repo: ${{ github.event.repository.name }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          tag-prefix: ''
